### ISSUE TITLE
Support for Handlebars

### ISSUE THREAD

**Issue by tsmith123** [keighl/mandrill#11]
Hi
I have a number of templates in my Mandrill account that use Handlebars (https://mandrill.zendesk.com/hc/en-us/articles/205582537-Using-Handlebars-for-dynamic-content) for dynamic content. Does this package support Handlebars at all?

Thanks

**Comment by keighl** [comment]
hey @tsmith123. I believe Handlebar templates in Mandrill are simply referencing `global_merge_vars`. So you should try passing merge variables like this:

`message.GlobalMergeVars = m.MapToVars(map[string]interface{}{"name": "Bob"})`

(from readme https://github.com/keighl/mandrill#including-merge-tags)

**Comment by tsmith123** [comment]
@keighl I did try that but I'm not sure how to specify the template.

Do I use `MessagesSend` or `MessagesSendTemplate`? The former only allows one argument so I can't specify my template and the latter requires three arguments, the third being some template content which of course doesn't exists using `message.GlobalMergeVars`.

Apologies if I've misunderstood something but any help would be much appreciated.

**Comment by keighl** [comment]
@tsmith123 `MessagesSendTemplate` is the correct method to use a template in your account. I'm a bit fuzzy on how mandrill negotiates the use of all the content sources (`global_merge_vars`, `merge_vars`, `template_content`). The docs aren't super clear (to me, at least).

The handlebars info implies `global_merge_vars`... but i dunno. I'd guess that one of these approaches should work:

``` go
////////////
// Using template content

message := &m.Message{}
message.AddRecipient("bob@example.com", "Bob Johnson", "to")
message.FromEmail = "kyle@example.com"
message.FromName = "Kyle Truscott"
message.Subject = "Mandrill Template Test #1"
templateContent := map[string]string{"name": "Bob"}

responses, err := client.MessagesSendTemplate(message, "tmpl-name", templateContent)

////////////
// Using "global" merge vars

message := &m.Message{}
message.AddRecipient("bob@example.com", "Bob Johnson", "to")
message.FromEmail = "kyle@example.com"
message.FromName = "Kyle Truscott"
message.Subject = "Mandrill Template Test #2"
message.GlobalMergeVars = m.MapToVars(map[string]interface{}{"name": "Bob"})

responses, err := client.MessagesSendTemplate(message, "tmpl-name", nil)

////////////
// Using "recipient" merge vars

message := &m.Message{}
message.AddRecipient("bob@example.com", "Bob Johnson", "to")
message.FromEmail = "kyle@example.com"
message.FromName = "Kyle Truscott"
message.Subject = "Mandrill Template Test #3"
bobVars := m.MapToRecipientVars("bob@example.com", map[string]interface{}{"name": "Bob"})
message.MergeVars = []*m.RcptMergeVars{bobVars}
responses, err := client.MessagesSendTemplate(message, "tmpl-name", nil)
```

**Comment by tsmith123** [comment]
I've tried them all and none appear to work!
Just noticed this question on SO too but it hasn't been answered: http://stackoverflow.com/questions/30917966/mandrill-global-merge-tags-not-working-using-keighl-mandrill-in-golang

**Comment by tsmith123** [comment]
Ah I've solved it - it requires a setting in the Mandrill account that I wasn't aware of so that the merge language is Handlebars. The link is included below. Sorry for the hassle.

https://mandrill.zendesk.com/hc/en-us/articles/205582537-Using-Handlebars-for-dynamic-content#choosing-handlebars-as-the-merge-language-for-your-emails

p.s. `GlobalMergeVars` is the way to go with Handlebars it appears.

**Comment by keighl** [comment]
Ah cool. With that setting, which "content" worked? Global merge vars?

**Comment by tsmith123** [comment]
Yeah - see my last comment.
I didn't think of setting the third argument to `nil`  in the `MessageSendTemplate` call so thanks for that.

**Comment by panamafrancis** [comment]
i found that the "merge_language" needs to be set to handlebars

```
message.MergeLanguage = "handlebars"
```
