### ISSUE TITLE
Possibly Incorrect Docs for ConvertMapToVariablesForRecipient

### ISSUE THREAD

**Issue by stilldavid** [keighl/mandrill#3]
In the readme and in code comments, the current usage shows:

```
message.MergeVars := m.ConvertMapToVariablesForRecipient("bob@example.com", map[string]string{"name": "Bob"})
```

Whereas in practice it should be something more like

```
message.MergeVars = []*m.RcptMergeVars{m.ConvertMapToVariablesForRecipient("bob@example.com", map[string]string{"name": "Bob"})}
```

Not a huge deal, but would be nice to change to help folks get started. I can submit a PR if it's convenient.

It might even be better as two lines of code instead of jamming it all on one, such as:

```
mergevars := m.ConvertMapToVariablesForRecipient("bob@example.com", map[string]string{"name": "Bob"})
message.MergeVars = []*m.RcptMergeVars{mergevars}
```

**Comment by keighl** [comment]
Hey @stilldavid, thanks for spotting that. I'd gladly take a PR. 

While we're on the subject, how do you feel about the method name  (`ConvertMapToVariablesForRecipient`). Looks my objc brain took over for a second. Got a more idiomatic name?
